import Timeline from "./Timeline";
import Headlines from "./Headlines";
import Economy from "./Economy";
import FamousPeople from "./FamousPeople";
import WorldMap from "./WorldMap";
import type { Scenario } from "../types";

interface DocumentaryProps {
  scenario: Scenario;
  question: string;
}

export default function Documentary({ scenario, question }: DocumentaryProps) {
  return (
    <article className="documentary">
      <header className="documentary-header">
        <span className="documentary-kicker">A WHAT IF? MACHINE ORIGINAL DOCUMENTARY</span>
        <h1 className="documentary-title">{scenario.title}</h1>
        <p className="documentary-question">“What if {question}?”</p>
        <p className="documentary-premise">{scenario.premise}</p>
        <div className="divergence-tag">
          Point of Divergence: <strong>{scenario.divergencePoint}</strong>
        </div>
      </header>

      <Timeline events={scenario.timeline} />
      <Headlines headlines={scenario.headlines} />
      <Economy economy={scenario.economy} />
      <FamousPeople people={scenario.famousPeople} />
      <WorldMap map={scenario.map} />

      <footer className="documentary-footer">
        End of transmission — this timeline is entirely fictional, generated by Gemini.
      </footer>
    </article>
  );
}
