import { motion } from "framer-motion";
import Timeline from "./Timeline";
import Headlines from "./Headlines";
import Economy from "./Economy";
import FamousPeople from "./FamousPeople";
import WorldMap from "./WorldMap";
import type { Scenario } from "../types";

interface DocumentaryProps {
  scenario: Scenario;
  question: string;
}

const sectionVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0 },
};

export default function Documentary({ scenario, question }: DocumentaryProps) {
  return (
    <motion.article
      initial="hidden"
      animate="visible"
      variants={{ visible: { transition: { staggerChildren: 0.12 } } }}
    >
      <motion.header
        variants={sectionVariants}
        className="mb-10 border-b border-border pb-8"
      >
        <span className="font-mono text-[0.7rem] tracking-[0.12em] text-accent">
          A WHAT IF? MACHINE ORIGINAL DOCUMENTARY
        </span>
        <h1 className="m-0 mt-2.5 mb-3 text-[2.8rem] leading-[1.1]">{scenario.title}</h1>
        <p className="m-0 mb-4 text-[1.1rem] italic text-text-dim">“What if {question}?”</p>
        <p className="max-w-180 text-[1.15rem] leading-[1.6]">{scenario.premise}</p>
        <div className="mt-4 inline-block rounded-full border border-accent-dim bg-accent/12 px-3.5 py-1.5 font-mono text-sm text-accent">
          Point of Divergence: <strong>{scenario.divergencePoint}</strong>
        </div>
      </motion.header>

      <motion.div variants={sectionVariants}>
        <Timeline events={scenario.timeline} />
      </motion.div>
      <motion.div variants={sectionVariants}>
        <Headlines headlines={scenario.headlines} />
      </motion.div>
      <motion.div variants={sectionVariants}>
        <Economy economy={scenario.economy} />
      </motion.div>
      <motion.div variants={sectionVariants}>
        <FamousPeople people={scenario.famousPeople} />
      </motion.div>
      <motion.div variants={sectionVariants}>
        <WorldMap map={scenario.map} />
      </motion.div>

      <motion.footer
        variants={sectionVariants}
        className="border-t border-border pt-6 text-center font-mono text-xs tracking-[0.04em] text-text-dim"
      >
        End of transmission — this timeline is entirely fictional, generated by Gemini.
      </motion.footer>
    </motion.article>
  );
}
